project:
  type: book
  output-dir: docs

book:
  title: Ecosystem Status Report Aleutian Islands, Bering Sea, and Gulf of Alaska
  subtitle: The subtitle
  date: March 2026
  downloads: [pdf, docx]
  author:
  - name: Bridget Ferriss
    email: Bridget.Ferriss AT noaa.gov 
    note: https://github.com/BridgetFerriss  
    affiliations:
      - name: NOAA Fisheres Alaska Fisheries Science Center
        department: Resource Ecology and Fisheries Management Division
        address: 
          - 7600 Sandpoint Way NE
          - Seattle, Washington 98115
      - id: uw-safs
        name: University of Washington
        department: School of Aquatic and Fisheries Sciences
    - name: Emily Markowitz
      email: Emily.Markowitz AT noaa.gov 
      orcid: 0000-0001-5757-4230
      note: https://github.com/EmilyMarkowitz-NOAA
      affiliations:
        - name: NOAA Fisheres Alaska Fisheries Science Center
          department: Groundfish Assessment Program
        address: 
          - 7600 Sandpoint Way NE
          - Seattle, Washington 98115
  chapters:
    - index.qmd
    - text/Chapter1.qmd
    - text/conclusion.qmd
    - text/references.qmd

  site-url: https://EmilyMarkowitz-NOAA.io/alaska-esr/
  repo-url: https://github.com/EmilyMarkowitz-NOAA/alaska-esr
  repo-actions: [edit, source, issue]
  search: true

bibliography: 
  - text/references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    cite-method: biblatex

metadata-files:
  - _frontmatter.yml
  
